### ISSUE TITLE
Keep getting this error 

### ISSUE THREAD

**Issue by EccoZulu** [nidea1/e-Auction#2]
![image](https://github.com/nidea1/e-Auction/assets/91420825/98691568-a7ed-492e-a15f-0d729183af5f)
Can't do anything, no mistypes in URLs

**Comment by nidea1** [comment]
Yes, you can't do anything really :) If you getting this error after frontend request please update frontend/src/actions urls.

**Comment by EccoZulu** [comment]
I'm not familiar with  Django and how it works, can you help me to run this project? What exactly should I change in the actions subfolder?

**Comment by nidea1** [comment]
This project is not for begginners. So you must learn Django (with python, javascript and react) fundamentals. But basically you can request to `localhost:8000/api/xxxx` after run server for using backend.

**Comment by EccoZulu** [comment]
> This project is not for begginners. So you must learn Django (with python, javascript and react) fundamentals. But basically you can request to `localhost:8000/api/xxxx` after run server for using backend.

I already figured it out, but thank you anyway. 
Unfortunately, I have another problem: 
This happens when I'm trying to log in, and I can't understand why is that password and email same as in DB
![image](https://github.com/nidea1/e-Auction/assets/91420825/a40e0f73-6bc2-4286-bda3-ee096d831d1c)
